version: "3.8"

services:
  dev:
    build: ./trainer
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - ./:/workspace
    working_dir: /workspace
    environment:
      - RUNS_DIR=/workspace/runs
    command:
      ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    